"""add vllm_version column to agents

Revision ID: 36cab2930a74
Revises: 20260607_1840
Create Date: 2026-06-09 02:12:49.012441
"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36cab2930a74'
down_revision: Union[str, None] = '20260607_1840'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_logs', 'id',
               existing_type=sa.BIGINT(),
               comment='Sequential PK for high-volume log ingestion',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('agent_logs', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Log timestamp (set by the agent)',
               existing_nullable=False)
    op.alter_column('agent_logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', name='loglevel'),
               comment='Log severity level',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::loglevel"))
    op.alter_column('agent_logs', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment='Source module or component name',
               existing_nullable=True)
    op.alter_column('agent_logs', 'message',
               existing_type=sa.TEXT(),
               comment='Log message body',
               existing_nullable=False)
    op.alter_column('agent_logs', 'stack_trace',
               existing_type=sa.TEXT(),
               comment='Optional exception stack trace',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'id',
               existing_type=sa.BIGINT(),
               comment='Sequential PK for high-frequency write throughput',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('agent_metrics', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Observation timestamp (set by the agent, not insert time)',
               existing_nullable=False)
    op.alter_column('agent_metrics', 'tier',
               existing_type=sa.VARCHAR(length=10),
               comment='Retention tier: raw, t10s, t1m, t10m, t1h, t6h',
               existing_nullable=False,
               existing_server_default=sa.text("'raw'::character varying"))
    op.alter_column('agent_metrics', 'gpu_util_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU utilization percentage 0–100',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_mem_used_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU memory used in MB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_temp_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU temperature in Celsius',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_power_w',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU power draw in watts',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_cache_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='GPU KV cache utilization percentage',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'running',
               existing_type=sa.INTEGER(),
               comment='Currently running requests',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'waiting',
               existing_type=sa.INTEGER(),
               comment='Queued / waiting requests',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'total_requests',
               existing_type=sa.INTEGER(),
               comment='Total requests since last reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'prompt_tokens_total',
               existing_type=sa.INTEGER(),
               comment='Total prompt tokens since reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gen_tokens_total',
               existing_type=sa.INTEGER(),
               comment='Total generated tokens since reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ttft_p50_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Time to first token p50 in ms',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ttft_p99_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Time to first token p99 in ms',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'tps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Tokens per second throughput',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'prefix_cache_hit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Prefix cache hit rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'error_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Request error rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'trunc_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Request truncation rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ram_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Host RAM used in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ram_total_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total host RAM in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'cpu_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Host CPU utilization percentage',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='System load average (1 minute)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='System load average (5 minutes)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_15',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='System load average (15 minutes)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'disk_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Disk space used in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'disk_total_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Total disk space in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'disk_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='Disk usage percentage',
               existing_nullable=True)
    op.alter_column('agent_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment='SHA-256 hash of the full registration token',
               existing_nullable=False)
    op.alter_column('agent_tokens', 'prefix',
               existing_type=sa.VARCHAR(length=8),
               comment='First 8 characters of the token for display/lookup',
               existing_nullable=False)
    op.alter_column('agent_tokens', 'agent_id',
               existing_type=sa.UUID(),
               comment='Agent that claimed this token (null until claimed)',
               existing_nullable=True)
    op.alter_column('agent_tokens', 'status',
               existing_type=postgresql.ENUM('pending', 'claimed', 'expired', name='tokenstatus'),
               comment='Current token lifecycle status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::tokenstatus"))
    op.alter_column('agent_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Token expiration timestamp',
               existing_nullable=False)
    op.drop_constraint(op.f('agent_tokens_token_hash_key'), 'agent_tokens', type_='unique')
    op.add_column('agents', sa.Column('vllm_version', sa.String(length=50), nullable=True, comment="Installed vLLM version, e.g. '0.6.0'"))
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Auto-generated friendly name, e.g. 'cyan-koala-42'",
               existing_nullable=False)
    op.alter_column('agents', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               comment='Server hostname reported by the agent at registration',
               existing_nullable=True)
    op.alter_column('agents', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               comment='SemVer of the installed modelprism-agent package',
               existing_nullable=True)
    op.alter_column('agents', 'status',
               existing_type=postgresql.ENUM('online', 'offline', name='agentstatus'),
               comment='Current agent connection status',
               existing_nullable=False,
               existing_server_default=sa.text("'offline'::agentstatus"))
    op.alter_column('agents', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Last heartbeat or successful communication timestamp',
               existing_nullable=True)
    op.alter_column('agents', 'gpu_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='GPU hardware details (model, count, VRAM per GPU, driver)',
               existing_nullable=True)
    op.alter_column('agents', 'cpu_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='CPU hardware details (model, cores, threads, architecture)',
               existing_nullable=True)
    op.alter_column('agents', 'disk_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='Disk information (mounts, total, used, filesystem types)',
               existing_nullable=True)
    op.alter_column('agents', 'os_info',
               existing_type=sa.VARCHAR(length=255),
               comment="Operating system identifier, e.g. 'Ubuntu 22.04'",
               existing_nullable=True)
    op.alter_column('agents', 'workspace_id',
               existing_type=sa.UUID(),
               comment='Optional workspace FK for future multi-tenancy (enforced in M4)',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'workspace_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Optional workspace FK for future multi-tenancy (enforced in M4)',
               existing_nullable=True)
    op.alter_column('agents', 'os_info',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Operating system identifier, e.g. 'Ubuntu 22.04'",
               existing_nullable=True)
    op.alter_column('agents', 'disk_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='Disk information (mounts, total, used, filesystem types)',
               existing_nullable=True)
    op.alter_column('agents', 'cpu_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='CPU hardware details (model, cores, threads, architecture)',
               existing_nullable=True)
    op.alter_column('agents', 'gpu_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='GPU hardware details (model, count, VRAM per GPU, driver)',
               existing_nullable=True)
    op.alter_column('agents', 'last_seen_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Last heartbeat or successful communication timestamp',
               existing_nullable=True)
    op.alter_column('agents', 'status',
               existing_type=postgresql.ENUM('online', 'offline', name='agentstatus'),
               comment=None,
               existing_comment='Current agent connection status',
               existing_nullable=False,
               existing_server_default=sa.text("'offline'::agentstatus"))
    op.alter_column('agents', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='SemVer of the installed modelprism-agent package',
               existing_nullable=True)
    op.alter_column('agents', 'hostname',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Server hostname reported by the agent at registration',
               existing_nullable=True)
    op.alter_column('agents', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Auto-generated friendly name, e.g. 'cyan-koala-42'",
               existing_nullable=False)
    op.drop_column('agents', 'vllm_version')
    op.create_unique_constraint(op.f('agent_tokens_token_hash_key'), 'agent_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('agent_tokens', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Token expiration timestamp',
               existing_nullable=False)
    op.alter_column('agent_tokens', 'status',
               existing_type=postgresql.ENUM('pending', 'claimed', 'expired', name='tokenstatus'),
               comment=None,
               existing_comment='Current token lifecycle status',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::tokenstatus"))
    op.alter_column('agent_tokens', 'agent_id',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='Agent that claimed this token (null until claimed)',
               existing_nullable=True)
    op.alter_column('agent_tokens', 'prefix',
               existing_type=sa.VARCHAR(length=8),
               comment=None,
               existing_comment='First 8 characters of the token for display/lookup',
               existing_nullable=False)
    op.alter_column('agent_tokens', 'token_hash',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='SHA-256 hash of the full registration token',
               existing_nullable=False)
    op.alter_column('agent_metrics', 'disk_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Disk usage percentage',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'disk_total_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total disk space in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'disk_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Disk space used in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_15',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='System load average (15 minutes)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_5',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='System load average (5 minutes)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'load_1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='System load average (1 minute)',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'cpu_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Host CPU utilization percentage',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ram_total_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Total host RAM in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ram_used_gb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Host RAM used in GB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'trunc_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Request truncation rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'error_rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Request error rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'prefix_cache_hit',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Prefix cache hit rate 0–1',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'tps',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Tokens per second throughput',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ttft_p99_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Time to first token p99 in ms',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'ttft_p50_ms',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='Time to first token p50 in ms',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gen_tokens_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total generated tokens since reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'prompt_tokens_total',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total prompt tokens since reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'total_requests',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total requests since last reset',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'waiting',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Queued / waiting requests',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'running',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Currently running requests',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_cache_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU KV cache utilization percentage',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_power_w',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU power draw in watts',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_temp_c',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU temperature in Celsius',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_mem_used_mb',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU memory used in MB',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'gpu_util_pct',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='GPU utilization percentage 0–100',
               existing_nullable=True)
    op.alter_column('agent_metrics', 'tier',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='Retention tier: raw, t10s, t1m, t10m, t1h, t6h',
               existing_nullable=False,
               existing_server_default=sa.text("'raw'::character varying"))
    op.alter_column('agent_metrics', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Observation timestamp (set by the agent, not insert time)',
               existing_nullable=False)
    op.alter_column('agent_metrics', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Sequential PK for high-frequency write throughput',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('agent_logs', 'stack_trace',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional exception stack trace',
               existing_nullable=True)
    op.alter_column('agent_logs', 'message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Log message body',
               existing_nullable=False)
    op.alter_column('agent_logs', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='Source module or component name',
               existing_nullable=True)
    op.alter_column('agent_logs', 'level',
               existing_type=postgresql.ENUM('debug', 'info', 'warning', 'error', name='loglevel'),
               comment=None,
               existing_comment='Log severity level',
               existing_nullable=False,
               existing_server_default=sa.text("'info'::loglevel"))
    op.alter_column('agent_logs', 'ts',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Log timestamp (set by the agent)',
               existing_nullable=False)
    op.alter_column('agent_logs', 'id',
               existing_type=sa.BIGINT(),
               comment=None,
               existing_comment='Sequential PK for high-volume log ingestion',
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
