"""Pydantic schemas for agent registration request/response.

Agent registration and token endpoints use plain ``application/json``
(not JSON:API).  Agent list and detail endpoints return JSON:API format
via ``app.schemas.jsonapi``.
"""

from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field

# --- Request Schemas ---


class AgentRegisterRequest(BaseModel):
    """Phase 1 (claim) request — lightweight, token + hostname only."""

    token: str = Field(
        ...,
        min_length=32,
        max_length=256,
        description="Registration token generated by the dashboard",
    )
    hostname: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Server hostname reported by the agent",
    )


class AgentCompleteRequest(BaseModel):
    """Phase 2 (complete) request — full hardware specifications."""

    gpus: list[GPUInfo] = Field(
        default_factory=list,
        description="List of GPU hardware details",
    )
    cpu: CPUInfo | None = Field(
        default=None,
        description="CPU hardware details",
    )
    disk: DiskInfo | None = Field(
        default=None,
        description="Disk information",
    )
    os: str | None = Field(
        default=None,
        max_length=255,
        description="Operating system identifier, e.g. 'Ubuntu 22.04'",
    )
    agent_version: str | None = Field(
        default=None,
        max_length=50,
        description="Agent package SemVer, e.g. '0.1.0'",
    )


class GPUInfo(BaseModel):
    """GPU hardware details for a single GPU."""

    name: str | None = Field(
        default=None,
        description="GPU model name, e.g. 'NVIDIA A100-SXM4-80GB'",
    )
    memory_total_mb: int | None = Field(
        default=None,
        ge=0,
        description="Total VRAM in megabytes",
    )
    driver_version: str | None = Field(
        default=None,
        description="NVIDIA driver version",
    )
    cuda_version: str | None = Field(
        default=None,
        description="CUDA version, e.g. '12.4'",
    )


class CPUInfo(BaseModel):
    """CPU hardware details."""

    model: str | None = Field(
        default=None,
        description="CPU model name",
    )
    cores: int | None = Field(
        default=None,
        ge=1,
        description="Number of CPU cores",
    )
    total_memory_gb: float | None = Field(
        default=None,
        ge=0,
        description="Total system RAM in gigabytes",
    )


class DiskInfo(BaseModel):
    """Disk storage details."""

    total_gb: float | None = Field(
        default=None,
        ge=0,
        description="Total disk capacity in gigabytes",
    )
    available_gb: float | None = Field(
        default=None,
        ge=0,
        description="Available disk space in gigabytes",
    )


# --- Response Schemas ---


class TokenResponse(BaseModel):
    """Response returned from the token generation endpoint."""

    token: str = Field(
        ...,
        description="The raw registration token (single-use, show once)",
    )
    prefix: str = Field(
        ...,
        max_length=8,
        description="First 8 characters of the token for display",
    )
    expires_at: datetime = Field(
        ...,
        description="Token expiry timestamp",
    )


class ClaimResponse(BaseModel):
    """Response returned after phase 1 (claim) of registration."""

    agent_id: str = Field(
        ...,
        description="Persistent agent identifier (UUID string)",
    )
    name: str = Field(
        ...,
        description="Auto-generated friendly agent name",
    )
    ws_url: str = Field(
        ...,
        description="WebSocket URL for agent communication",
    )


class CompleteResponse(BaseModel):
    """Response returned after phase 2 (complete) of registration."""

    agent_id: str = Field(
        ...,
        description="Persistent agent identifier",
    )
    name: str = Field(
        ...,
        description="Auto-generated friendly agent name",
    )
    ws_url: str = Field(
        ...,
        description="WebSocket URL for agent communication",
    )
    config: AgentConfig = Field(
        ...,
        description="Agent runtime configuration",
    )


class AgentConfig(BaseModel):
    """Agent runtime configuration returned after complete registration."""

    poll_interval_seconds: int = Field(
        default=2,
        ge=1,
        description="How often the agent should push metrics (seconds)",
    )
    heartbeat_interval_seconds: int = Field(
        default=15,
        ge=1,
        description="How often the agent should send heartbeats (seconds)",
    )
